### ISSUE TITLE
Suffix letters and decimals aren't showing up

### ISSUE THREAD

**Issue by FortyOneNY** [cogwerkz/Bagnon_ArtifactPower#1]
![wowscrnshot_031018_150605](https://user-images.githubusercontent.com/20746872/37246305-fd742a7c-2474-11e8-96e0-e9641e731b39.jpg)

I only had Bagnon and Bagnon_ArtifactPower enabled when I took the attached screenshot. As you can see, the suffix letters and decimals are missing completely. I can live without the decimals (though I'd prefer not to), but it would be nice to have the letters there.

**Comment by goldpaw** [comment]
more or less fixed in 1.1.5
